name: radjay
favicon: null
layout_spectrum: 0.5044583913404495
typography_spectrum: 0.18337352853268385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9e0203'
    - '#ce2e32'
    - '#be7374'
    - '#949494'
  brandStrength: 0.7668983284384012
  lightness: 0.45913619501516223
  saturation: 0.75
  rhythmicContrast: 0.4049624118488282
purpose: []
